version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: symfony-crm/Dockerfile
      target: prod
    container_name: web_app
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - APP_ENV
      - APP_SECRET
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db_app
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
